# Generated by Django 3.2.7 on 2021-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210916_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00 am - 09:30 am', '09:00 am - 09:30 am'), ('09:30 am - 10:00 am', '09:30 am - 10:00 am'), ('10:00 am - 10:30 am', '10:00 am - 10:30 am')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availabity',
            name='time',
            field=models.CharField(choices=[('09:00 am - 09:30 am', '09:00 am - 09:30 am'), ('09:30 am - 10:00 am', '09:30 am - 10:00 am'), ('10:00 am - 10:30 am', '10:00 am - 10:30 am')], max_length=20, null=True),
        ),
    ]
