# Generated by Django 3.2.7 on 2021-09-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctoruser_specilization'),
        ('mainapp', '0003_auto_20210916_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser'),
        ),
        migrations.AlterField(
            model_name='availabity',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctoruser'),
        ),
    ]
