# Generated by Django 3.2.7 on 2021-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210916_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabity',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
