# Generated by Django 3.2.7 on 2021-09-16 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specilization_type', models.CharField(max_length=255)),
                ('problem_related', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(null=True)),
                ('total_experience_years', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('maximum_degree', models.ImageField(upload_to='doctors_degree')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='doctors_pics')),
                ('admin_approve', models.BooleanField(default=False)),
                ('specilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.specilization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
